export const profile = {
  name: "Aniket Yadav",
  firstName: "Aniket",
  role: "B.Tech CSE Core Student",
  college: "Chandigarh University, Unnao Campus",
  location: "India",
  github: "https://github.com/ANIKET-YADAV679",
  linkedin: "https://www.linkedin.com/in/aniket-yadav-030797379",
  leetcode: "https://leetcode.com/u/Aniket_Yadav_679/",
  bio: "I'm a CSE student who enjoys turning ideas into working projects, learning by building, and strengthening my problem-solving skills through code.",
  about: "I'm currently pursuing B.Tech in Computer Science & Engineering (Core) at Chandigarh University, Unnao Campus. I like learning the fundamentals, applying them to practical projects, and improving each project as I learn more.",
  philosophy: "Learn the fundamentals. Build something real. Solve the problems that appear. Repeat.",
};

export const skills = [
  { name: "HTML", type: "Web", level: "Building" },
  { name: "CSS", type: "Web", level: "Building" },
  { name: "JavaScript", type: "Web", level: "Learning" },
  { name: "SQL", type: "Database", level: "Learning" },
  { name: "C", type: "Programming", level: "Fundamentals" },
  { name: "Python", type: "Programming", level: "Building" },
  { name: "Java", type: "Programming", level: "Building" },
];

export const projects = [
  {
    slug: "devdiary",
    title: "DevDiary",
    category: "Web",
    year: "2026",
    stack: ["HTML", "CSS", "JavaScript"],
    description: "A developer learning tracker for recording daily progress, maintaining learning streaks, setting goals, and visualizing growth.",
    repo: "https://github.com/ANIKET-YADAV679/DevDiary",
    featured: true,
    symbol: "DD",
    accent: "violet",
    features: ["Daily learning logs", "Progress and streak tracking", "Goal-oriented workflow", "Developer-focused UI"],
  },
  {
    slug: "gamevault",
    title: "GameVault",
    category: "Web",
    year: "2026",
    stack: ["JavaScript", "HTML", "CSS"],
    description: "A gaming-focused web project built to explore interactive interfaces and practical front-end development.",
    repo: "https://github.com/ANIKET-YADAV679/GameHub",
    featured: true,
    symbol: "GV",
    accent: "cyan",
    features: ["Gaming interface", "Interactive components", "Responsive layout", "Front-end practice"],
  },
  {
    slug: "leetcode-helper",
    title: "LeetCode Helper Skill",
    category: "Tools",
    year: "2026",
    stack: ["Problem Solving", "AI", "LeetCode"],
    description: "A custom helper skill focused on making LeetCode problem solving more structured, practical, and interview-oriented.",
    repo: "https://github.com/ANIKET-YADAV679/LEET-CODE_HELPER-SKILL",
    featured: true,
    symbol: "LC",
    accent: "emerald",
    features: ["Problem-solving workflow", "Pattern-focused thinking", "Interview-oriented solutions", "Reusable guidance"],
  },
  {
    slug: "learning-dsa",
    title: "Learning DSA",
    category: "DSA",
    year: "2026",
    stack: ["C++", "DSA", "LeetCode"],
    description: "A growing collection of coding problems from LeetCode, GeeksforGeeks, and HackerRank built around consistent DSA practice.",
    repo: "https://github.com/ANIKET-YADAV679/LEARNING-DSA",
    featured: true,
    symbol: "DSA",
    accent: "amber",
    features: ["DSA practice", "Coding problem solutions", "Algorithm patterns", "Consistent learning"],
  },
  {
    slug: "snake-game",
    title: "Snake Game",
    category: "Java",
    year: "2026",
    stack: ["Java"],
    description: "A classic Snake game built as a practical Java project and an exercise in application logic and object-oriented programming.",
    repo: "https://github.com/ANIKET-YADAV679/SnakeGame",
    featured: false,
    symbol: "SG",
    accent: "pink",
    features: ["Classic Snake gameplay", "Java implementation", "Game loop logic", "Practical OOP exercise"],
  },
];